### PR TITLE
add thumbnails

### PR DESCRIPTION
**Pull request by idilsezgin**
Thumbnails for all videos are added.

### CODE REVIEW

**Review by egekorkan — APPROVED** [review]

**Review by relu91 — APPROVED** [review]
Is there the chance to improve the thumbnail later? it is ok for now, but I feel the subtitle has too low contrast... it makes reading long subtitles difficult. I suggest playing a little bit more with the typography... or simply increase saturation.

**Comment by egekorkan** [comment]
We can update thumbnails anytime we want in YouTube (some YouTubers even change it strategically over time). Ideally, to keep the effort low, we do not want to create a completely new thumbnail. @idilsezgin maybe increasing the contrast when generating the thumbnails is a good idea. Can you try different versions in one of them and post screenshots in this PR as comments?

**Comment by FadySalama** [comment]
I discussed today with Idil that the subtitle is the main problem. A green color for the thumbnail could be a great way to increase contrast and introduce a bit of variety in the title

**Comment by idilsezgin** [comment]
I have these two options: 

I feel like the darker one is easier to read however, the lighter one suits the color pallet better.
Screenshot 2023-11-10 at 12 09 27
Screenshot 2023-11-10 at 12 09 54

**Comment by egekorkan** [comment]
First I have thought that we should go with the dark green only for the thumbnails and the videos should have the light green but that would create more manual work. 

I think that the light green is fine. @idilsezgin can you apply the color to all thumbnails?

**Comment by egekorkan** [comment]
With the latest changes, it looks better in a thumbnail. Merging

**Pull request merged**
