### PR TITLE
Create markdown meeting minutes

### PR DESCRIPTION
**Pull request by egekorkan**
Continuing the initial ideas at https://github.com/w3c/wot-cg/discussions/14 I have done a first try. I have used some features of the Hackmd that seem to not be supported there. For a version at hackmd, see https://hackmd.io/@egekorkan/ByYhGDWro

The main problem is the usage of `:::` but that can be considered a minor feature. We can also remove those dots each time we bring the minutes over to github

### CODE REVIEW

**Comment by egekorkan** [comment]
With @relu91 we think that this is a quite good approach. We will introduce it in the next internal meeting

**Review by relu91 — APPROVED** [review]

**Comment by egekorkan** [comment]
@relu91 I have done the MD minutes of the HTML minutes we had. Have a quick look, then I will do the newer meetings that are not in the repo yet

**Review by relu91 — APPROVED** [review]
The changes look good, but we have to remember to update the main readme file cause it refers to the old minute taking process.

**Comment by egekorkan** [comment]
> The changes look good, but we have to remember to update the main readme file cause it refers to the old minute taking process.

I will quickly do that too :)

**Comment by egekorkan** [comment]
@relu91 I have changed the readme too

**Review by relu91 — APPROVED** [review]

**Pull request merged**
