### PR TITLE
Final adjustments to all videos

### LINKED ISSUE #153: Higher resolution videos
The video resolution is capped due to Murf.ai but technically we can export higher-resolution videos from powerpoint. We can discuss it in tomorrow's call if there is an easy way. The not easy way is to put audio and video into a video editor and quickly combine them.

### LINKED ISSUE #168: Line Numbers for all Code Snippets
As explained at https://docusaurus.io/docs/markdown-features/code-blocks#line-numbering, we can add line numbers to all code snippets. It makes it easier to screenshot and use in the videos like a small IDE.

### PR DESCRIPTION
**Pull request by Tedoshiii**
### Links to All Videos

1. Intro: https://murf.ai/share/ltbi0yp1
2. Payloads and Headers: https://murf.ai/share/lt8jnbs9
3. JSON Intro: https://murf.ai/share/lloyg2oe
4. JSON in Practice: https://murf.ai/share/lm6azmy3
5. JSON Schema Intro: https://murf.ai/share/lmxobdkm
6. JSON Schema in Practice: https://murf.ai/share/lmxop7cw
7. JSON Schema in Practice - Advanced Topics: https://murf.ai/share/lmxp40ar
8. JSON Schema in Practice - Validators: https://murf.ai/share/lmxpv0ix
9. OSI Layers: https://murf.ai/share/lo7ro6z8

### Upscaling all videos

- Videos 1 through 9 have been reuploaded with with a higher resolution of 1080p. closes #153

### Changes to code snippets

- Implemented animations for some of the code snippets, which emulate a real programming IDE. Code keyword colors conform to our chosen color scheme from #162 
- Changed videos: "2. Payloads and headers", "4. JSON in practice", "8. JSON Schema in practice"

### Additional feedback applied

- Implemented all feedback to "4. JSON in practice" from #167 
- Implemented feedback to "8. JSON Schema in practice" from #166 

### Website changes

- Closes #168, line numbering has been added to the appropriate code examples.

### CODE REVIEW

**Comment by egekorkan** [comment]
@TallTed let us know if there is any changes needed. We aim to merge and publish these on YouTube in one week

**Comment by TallTed** [comment]
Don't hold things up on my account. If I flag something after publication, it can be a note for the next iteration (as there's always another round).

**Comment by egekorkan** [comment]
> Don't hold things up on my account. If I flag something after publication, it can be a note for the next iteration (as there's always another round).

Ok thank you very much :) Our plan is to do a yearly re-publication since once the videos are on YouTube, there would be more feedback.

**Comment by egekorkan** [comment]
Small change needed for video 1: Around 3:00, before "If you are ready to dive in...", there is not enough pause. I thought this was fixed before?

**Comment by Tedoshiii** [comment]
> Small change needed for video 1: Around 3:00, before "If you are ready to dive in...", there is not enough pause. I thought this was fixed before?

Fixed with latest commit

**Pull request merged**
