### PR TITLE
10th video pptx added for review.

### PR DESCRIPTION
**Pull request by idilsezgin**
10th - Application Domains pptx added for review.

- visuals, text, and animations to be reviewed.

### CODE REVIEW

**Comment by egekorkan** [comment]
Slide 13: I think we should be extendable about the number of categories. 

Now, Let us introduce the WoT application domains which we categorize under 4 different headings, Smart Homes, Industrial Applications, Agriculture, and Smart Cities.  -> Now, let us introduce some of the WoT application domains: Smart Homes, Industrial Applications, Agriculture, and Smart Cities.  

Slide 14: we can remove "that is in the home". I think you want to say that to bridge to the architecture patterns but it sounds weird at this stage.

Slide 22: intermediary like **a** cloud application

Slide 23: I get confused a bit. We can discuss in a call?

Slide 26: What you mention by requirements are actually use cases. We should think together in a call.

**Comment by idilsezgin** [comment]
Slides number 13, 14, and 22 are resolved. 23 and 26 will be discussed in the meeting.

**Comment by egekorkan** [comment]
Slide 26: They have to support more complex use cases such as ...

**Comment by egekorkan** [comment]
My concerns are addressed, merging

**Pull request merged**
